services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
#    user: "${UID}:${GID}"
    user: "1000:1000"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/app
  db:
    env_file: ".env"
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  db-data:
