services:
  app:
    build:
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    #    user: "${UID}:${GID}"
    user: "1000:1000"
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - ./:/app
  db:
    env_file: ".env"
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  redis:
    env_file: ".env"
    image: redis:8-alpine3.21
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
volumes:
  db-data:
  redis-data:
